name: Update Rules

on:
  workflow_dispatch:
  schedule:
    - cron: "3 16 * * *"
  push:
    paths:
      - rules/*/manifest.yaml

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - run: |
            bash .github/scripts/build.sh rules -s
